# Generated by Django 4.0 on 2023-10-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
